In [1]:
import pandas as pd
import datetime
import numpy as np

In [2]:

# This is a list from winemag, through kaggle.com

# Read csv into pandas
wm_df=pd.read_csv('winemag-data-130k-v2.csv')

# Add source column and fill with 'WM'
wm_df['source']='WM'

# Extract vintage year from title (not all wines have a vintage provided)
info_vin=wm_df["title"]
vint=[]
for v in info_vin:
    vin_yr=''
    for i in v.split():
        if i.isdigit():
            vin_yr=vin_yr+i
    if vin_yr=='':
        vint.append('NaN')
    else:
        vint.append(int(vin_yr))
wm_df['vintage']=vint

wm_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,source,vintage
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,WM,2013
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,WM,2011
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,WM,2013
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,WM,2013
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,WM,2012

In [3]:
# wines.xlsx is from dataworld

# using pd.read_excel to read the xlsx file
wine_df = pd.read_excel('Wines.xlsx')

# Add source column and fill with 'DM'
wine_df['source']='DM'

# Change the vintage from datetime or string to interger year (both formats were in the excel file)
vin=wine_df["Vintage"]
vin_year=[]
for v in vin:
    if type(v)==datetime.datetime:
        vin_year.append(int(v.year))
    else:
        vin_year.append(int(v[4:8]))
wine_df["Vintage"]=vin_year
wine_df.head()

,Vintage,Country,County,Designation,Points,Price,Province,Title,Variety,Winery,source
0,1919,Spain,Cava,1919 Brut Selecció,88,$13.00,Catalonia,L'Arboc NV 1919 Brut Selecció Sparkling (Cava),Sparkling Blend,L'Arboc,DM
1,1929,Italy,Vernaccia di San Gimignano,NaN,87,$14.00,Tuscany,Guidi 1929 2015 Vernaccia di San Gimignano,Vernaccia,Guidi 1929,DM
2,1929,Italy,Sangiovese di Romagna Superiore,Prugneto,84,$15.00,Central Italy,Poderi dal Nespoli 1929 2011 Prugneto (Sangiov...,Sangiovese,Poderi dal Nespoli 1929,DM
3,1934,Portugal,NaN,Reserva Velho,93,$495.00,Colares,Adega Viuva Gomes 1934 Reserva Velho Red (Cola...,Ramisco,Adega Viuva Gomes,DM
4,1945,France,Rivesaltes,Legend Vintage,95,$350.00,Languedoc-Roussillon,Gérard Bertrand 1945 Legend Vintage Red (Rives...,Red Blend,Gérard Bertrand,DM

In [4]:
# Clean the Winemag-130k-v2 File

#Set the First Column Name as ID
wm_df1 = wm_df.rename(columns={'Unnamed: 0':'id'})

#Drop Unneeded Columns
wm_df_mod = wm_df1[['id', 'country', 'designation', 'points',
       'price', 'title', 'variety', 'winery', 'source',
       'vintage']]
#making a copy of the file
wm_df_mod1= wm_df_mod.copy()
#dropping NANs
wm_df_mod2= wm_df_mod1.dropna()
#counting the number of rows
wm_df_mod2.count()

id             86148
country        86148
designation    86148
points         86148
price          86148
title          86148
variety        86148
winery         86148
source         86148
vintage        86148
dtype: int64

In [5]:
wm_df_mod2.head()

,id,country,designation,points,price,title,variety,winery,source,vintage
1,1,Portugal,Avidagos,87,15.0,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,WM,2011
3,3,US,Reserve Late Harvest,87,13.0,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,WM,2013
4,4,US,Vintner's Reserve Wild Child Block,87,65.0,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,WM,2012
5,5,Spain,Ars In Vitro,87,15.0,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem,WM,2011
6,6,Italy,Belsito,87,16.0,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo,WM,2013

In [6]:
#checking columns in the wine.df dataframe(xlsx file)
wine_df.columns

Index(['Vintage', 'Country', 'County', 'Designation', 'Points', 'Price',
       'Province', 'Title', 'Variety', 'Winery', 'source'],
      dtype='object')

In [7]:
#only keeping the below columns and renaming the dataframe
wine_df_mod = wine_df[['Vintage', 'Country', 'Designation', 'Points', 'Price',
       'Title', 'Variety', 'Winery', 'source']]

In [8]:
#making a copy
wine_df_mod1= wine_df_mod.copy()

In [9]:

#dropping the Nans 
wine_df_mod2 = wine_df_mod1.dropna()

#restting the index
wine_df_mod2 = wine_df_mod2.reset_index()

#renaming the columns
wine_df_mod2= wine_df_mod2.rename(columns={'index':'id','Vintage':'vintage','Title':'title','Points':'points','Price':'price',
                                           'Country':'country','Designation':'designation','Variety':'variety',
                                           'Winery':'winery'})

In [10]:
wine_df_mod2.columns

Index(['id', 'vintage', 'country', 'designation', 'points', 'price', 'title',
       'variety', 'winery', 'source'],
      dtype='object')

In [11]:
wm_df_mod2.columns

Index(['id', 'country', 'designation', 'points', 'price', 'title', 'variety',
       'winery', 'source', 'vintage'],
      dtype='object')

In [12]:
#rearranging the column so that both dataframes have same order of columns
wine_df_mod2 = wine_df_mod2[['id', 'country', 'designation', 'points', 'price',
       'title', 'variety', 'winery', 'source', 'vintage']]

In [13]:
#appending the columns
wine_df_appended = wm_df_mod2.append(wine_df_mod2)

In [14]:
#Reset the Index
wine_df_appended = wine_df_appended.reset_index(drop=True)
wine_df_appended = wine_df_appended.drop(columns=['id'])
#wine_df_appended = wine_df_appended.rename(columns={'index','id'})

wine_df_appended.head()

,country,designation,points,price,title,variety,winery,source,vintage
0,Portugal,Avidagos,87,15,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,WM,2011
1,US,Reserve Late Harvest,87,13,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,WM,2013
2,US,Vintner's Reserve Wild Child Block,87,65,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,WM,2012
3,Spain,Ars In Vitro,87,15,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem,WM,2011
4,Italy,Belsito,87,16,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo,WM,2013

In [15]:
#grouping the dataframe by title to see the most popular wines and sorting by points
wine_df_grouped = wine_df_appended.groupby('title').mean()

wine_df_sorted = wine_df_grouped.sort_values('points',ascending= False)
wine_df_sorted

                                                    points
title
Tenuta dell'Ornellaia 2007 Masseto Merlot (Tosc...   100.0
Casa Ferreirinha 2008 Barca-Velha Red (Douro)        100.0
Salon 2006 Le Mesnil Blanc de Blancs Brut Chard...   100.0
Avignonesi 1995 Occhio di Pernice  (Vin Santo d...   100.0
Krug 2002 Brut  (Champagne)                          100.0
...                                                    ...
Spann Vineyards 2004 Twenty-Three Barrels Mo Jo...    80.0
Midnight 2006 Estate Reserve Chardonnay (Paso R...    80.0
Cuevas del Sur 2010 Reserve Chardonnay (Maule V...    80.0
Ernesto Catena 2014 Padrillos Malbec (Mendoza)        80.0
Viñedos Altamira Valley 2011 VAV Malbec (Valle ...    80.0

[81661 rows x 1 columns]

In [16]:
from sqlalchemy import create_engine 

#Create Database Connection
connection_string = "postgres:postgres@localhost:5432/wines_db"
engine = create_engine(f'postgresql://postgres:postgres@localhost:5432/wines_db')